---
# tasks file for update-config

- name: get node id
  ansible.builtin.command:
    cmd: >
      {{ simd }} tendermint show-node-id --home {{ simd_home }}
  register: node_id_output
  changed_when: false

- name: make list of peers
  ansible.builtin.set_fact:
    peer_list: |
      {% set peers = [] %}
      {% for host in ansible_play_hosts %}
      {% if host != inventory_hostname %}
      {% set _ = peers.append(hostvars[host].node_id_output.stdout ~ '@' ~ hostvars[host].ansible_host ~ ':26656') %}
      {% endif %}
      {% endfor %}
      {{ peers }}

- name: set persistent_peers for a full mesh network
  ansible.builtin.lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^persistent_peers ='
    line: 'persistent_peers = "{{ peer_list | join(",") }}"'

- name: set block proposal timeout (timeout_propose)
  ansible.builtin.lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_propose ='
    line: 'timeout_propose = "400ms"'

# - name: set block proposal timeout (timeout_propose_delta)
#   ansible.builtin.lineinfile:
#     path: "{{ simd_home }}/config/config.toml"
#     regexp: '^timeout_propose_delta ='
#     line: 'timeout_propose_delta = "50ms"'

- name: set prevote timeout (timeout_prevote)
  ansible.builtin.lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_prevote ='
    line: 'timeout_prevote = "0ms"'

# - name: set prevote timeout (timeout_prevote_delta)
#   ansible.builtin.lineinfile:
#     path: "{{ simd_home }}/config/config.toml"
#     regexp: '^timeout_prevote_delta ='
#     line: 'timeout_prevote_delta = "10ms"'

- name: set precommit timeout (timeout_precommit)
  ansible.builtin.lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_precommit ='
    line: 'timeout_precommit = "0ms"'

# - name: set precommit timeout (timeout_precommit_delta)
#   ansible.builtin.lineinfile:
#     path: "{{ simd_home }}/config/config.toml"
#     regexp: '^timeout_precommit_delta ='
#     line: 'timeout_precommit_delta = "10ms"'

- name: set commit timeout (timeout_commit)
  ansible.builtin.lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^timeout_commit ='
    line: 'timeout_commit = "0ms"'

- name: activation of metric
  ansible.builtin.lineinfile:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^prometheus ='
    line: 'prometheus = true'
    insertafter: '^\[instrumentation\]'

- name: set laddr 0.0.0.0
  ansible.builtin.replace:
    path: "{{ simd_home }}/config/config.toml"
    regexp: '^laddr = "tcp://[^:]+:(\d+)"'
    replace: 'laddr = "tcp://0.0.0.0:\1"'

- name: deploy app setting file
  ansible.builtin.template:
    src: app.toml.j2
    dest: "{{ simd_home }}/config/app.toml"