---
# tasks file for init-network

- name: delete home directory
  ansible.builtin.file:
    path: "{{ simd_home }}"
    state: absent

- name: delete genesis related files in gen directory
  ansible.builtin.shell:
    cmd: "rm -rf ~/cosmos-sdk-example/gen/*"
  delegate_to: localhost
  run_once: true

- name: simd init
  ansible.builtin.command: 
    cmd: >
      {{ simd }} init {{ moniker }} --chain-id {{ chain_id }} --home {{ simd_home }}
