---
# tasks file for init-network

- name: create systemd service file for simd
  ansible.builtin.template:
    src: simd.service.j2
    dest: /etc/systemd/system/simd.service
    owner: root
    group: root
    mode: '0644'
  become: yes

- name: ensure simd service is stoped and enabled
  ansible.builtin.systemd:
    name: simd
    state: stopped
    enabled: yes
    daemon_reload: yes
  become: yes

- name: delete home directory
  ansible.builtin.file:
    path: "{{ simd_home }}"
    state: absent

- name: delete genesis related files in gen directory
  ansible.builtin.shell:
    cmd: "rm -rf ~/cosmos-sdk-example/gen/*"
  delegate_to: localhost
  run_once: true

- name: simd init
  ansible.builtin.command: 
    cmd: >
      {{ simd }} init {{ moniker }} --chain-id {{ chain_id }} --home {{ simd_home }}
