---
# tasks file for init-network

- name: delete home directory
  ansible.builtin.file:
    path: "{{ simd_home }}"
    state: absent
  become: yes

- name: simd init
  ansible.builtin.command: 
    cmd: >
      {{ simd }} init {{ moniker }} --chain-id {{ chain_id }} --home {{ simd_home }}
  become: yes
