---
# tasks file for make-key

- name: check validator key
  ansible.builtin.stat:
    path: "{{ simd_home }}/keyring-test/{{ key_name }}.info"
  register: key_check

- name: create validator key
  ansible.builtin.command:
    cmd: >
      simd keys add {{ key_name }} --keyring-backend test --home {{ simd_home }}
  when: not key_check.stat.exists

- name: set validator address
  ansible.builtin.command:
    cmd: > 
      simd keys show {{ key_name }} --address --keyring-backend test --home {{ simd_home }}
  register: validator_address
