---
# tasks file for generate-transaction
- name: "add faucet to all of node address"
  when: inventory_hostname == "seoul"
  ansible.builtin.command:
    cmd: >
      {{ simd }} genesis add-genesis-account {{ hostvars[item].validator_address.stdout }} {{ init_amount }} --home {{ simd_home }}
  loop: "{{ ansible_play_hosts }}"

- name: get seoul genesis file
  when: inventory_hostname == "seoul"
  ansible.builtin.shell:
    cmd: >
      scp -i {{ ansible_ssh_private_key_file }} 
      {{ ansible_user }}@{{ ansible_host }}:'{{ simd_home }}/config/genesis.json' 
      ~/cosmos-sdk-example/gen/
  delegate_to: localhost

- name: genesis file to all of node
  ansible.builtin.shell:
    cmd: >
      scp -i {{ ansible_ssh_private_key_file }} 
      ~/cosmos-sdk-example/gen/genesis.json
      {{ ansible_user }}@{{ ansible_host }}:{{ simd_home }}/config/genesis.json
  delegate_to: localhost

- name: "add stake transaction"
  ansible.builtin.command: 
    cmd: > 
      {{ simd }} genesis gentx {{ key_name }} {{ stake_amount }} --chain-id {{ chain_id }} --keyring-backend test --home {{ simd_home }}

- name: get all of transaction file except seoul
  when: inventory_hostname != "seoul"
  ansible.builtin.shell:
    cmd: >
      scp -i {{ ansible_ssh_private_key_file }} 
      {{ ansible_user }}@{{ ansible_host }}:'{{ simd_home }}/config/gentx/*.json' 
      ~/cosmos-sdk-example/gen/
  delegate_to: localhost

- name: santiago transaction file to seoul node
  when: inventory_hostname == "seoul"
  ansible.builtin.shell:
    cmd: >
      scp -i {{ ansible_ssh_private_key_file }} 
      ~/cosmos-sdk-example/gen/gentx-*.json
      {{ ansible_user }}@{{ ansible_host }}:{{ simd_home }}/config/gentx/
  delegate_to: localhost

- name: merge transactions
  when: inventory_hostname == "seoul"
  ansible.builtin.command: 
    cmd: >
      {{ simd }} genesis collect-gentxs --home {{ simd_home }}
  run_once: true

- name: get seoul final genesis file
  when: inventory_hostname == "seoul"
  ansible.builtin.shell:
    cmd: >
      scp -i {{ ansible_ssh_private_key_file }} 
      {{ ansible_user }}@{{ ansible_host }}:'{{ simd_home }}/config/genesis.json' 
      ~/cosmos-sdk-example/gen/
  delegate_to: localhost

- name: final genesis file to all of node
  ansible.builtin.shell:
    cmd: >
      scp -i {{ ansible_ssh_private_key_file }} 
      ~/cosmos-sdk-example/gen/genesis.json
      {{ ansible_user }}@{{ ansible_host }}:{{ simd_home }}/config/genesis.json
  delegate_to: localhost
