---
# tasks file for generate-transaction

- name: "add faucet to seoul address"
  when: inventory_hostname == "seoul"
  ansible.builtin.command: 
    cmd: > 
      {{ simd }} genesis add-genesis-account {{ seoul_address }} {{ init_amount }} --home {{ simd_home }}

- name: "add faucet to santiago address"
  when: inventory_hostname == "seoul"
  ansible.builtin.command: 
    cmd: > 
      {{ simd }} genesis add-genesis-account {{ santiago_address }} {{ init_amount }} --home {{ simd_home }}

- name: "add stake transaction"
  ansible.builtin.command: 
    cmd: > 
      {{ simd }} genesis gentx {{ key_name }} {{ stake_amount }} --chain-id {{ chain_id }} --keyring-backend test --home {{ simd_home }}

- name: get santiago transaction file
  when: inventory_hostname == "santiago"
  ansible.builtin.fetch:
    src: ~/{{ simd_home }}/config/gentx/*.json
    dest: /tmp/
    flat: yes

- name: santiago transaction file to seoul node
  when: inventory_hostname == "seoul"
  ansible.builtin.copy:
    src: /tmp/config/gentx/*.json
    dest: ~/{{ simd_home }}/config/gentx/*.json

- name: merge transactions
  when: inventory_hostname == "seoul"
  command: >
    {{ simd }} genesis collect-gentxs --home {{ simd_home }}
  run_once: true

- name: get genesis file
  when: inventory_hostname == "seoul"
  ansible.builtin.fetch:
    src: ~/{{ simd_home }}/config/genesis.json
    dest: /tmp/
    flat: yes

- name: seoul genesis file to santiago node
  when: inventory_hostname == "seoul"
  ansible.builtin.copy:
    src: /tmp/config/genesis.json
    dest: ~/{{ simd_home }}/config/genesis.json
